name: CI
run-name: ${{ github.actor }} is testing Actions
env:
  GITHUB_ACTIONS: true
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: github-task-job
        run: echo "run on the latest version of ${{ github.label }} is ${{ env.GITHUB_ACTIONS }}"

      - name: show the name of the branch and repository
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
      - name: initiated event name the workflow
        run: |
          echo "Event: ${{ github.event_name }}"
      
